update:
  only:
    - tags
    - triggers
  before_script:
    # Abhängigkeiten überprüfen
    - which composer
    - which git
  script:
    # Pfad zum neu geklonten Repo
    - path=`pwd`
    - cd ~/
    - git clone "$path" MetaGer_neu
    - cd MetaGer_neu
    - composer update
    - cd ~/
    - rm -rf MetaGer
    - mv MetaGer_neu MetaGer