update:
  only:
    - tags
    - triggers
  before_script:
    # Abhängigkeiten überprüfen
    - which virtualbox
    - which vagrant
    - which composer
    - which git
    - which php
  script:
    # Pfad zum neu geklonten Repo
    - path=`pwd`
    - cd ~/
    - $path/deploy/checkServerStatus.sh "$path"
    - cd ~/MetaGerssas
    - git pull "$path"